### ISSUE TITLE
Dockerize RNAmigos

### ISSUE THREAD

**Issue by rayanosseiran** [TeamW-P/RNAmigos#1]
Implement a simple dockerization of RNAmigos. The goal should be to:

- Set-up a simple flask app (no routing or actual work yet, just set-up a hello world response).
- Restructure file structure (core, routes).
- Define environment & dockerfile.

**Comment by 1jayyaj1** [comment]
Gonna take it on - thanks @rayano24

**Comment by rayanosseiran** [comment]
Implemented in [PR#2](https://github.com/TeamW-P/RNAmigos/pull/2)
